### ISSUE TITLE
Wait upon certain time for incoming packets

### ISSUE THREAD

**Issue by kienhg96** [mas-bandwidth/netcode#116]
Hi, it's me again.

I discovered that in ENet, the function`enet_host_service` which takes the last argument `timeout` to wait for the next incoming packets.
[https://github.com/lsalzman/enet/blob/master/protocol.c#L1788](https://github.com/lsalzman/enet/blob/master/protocol.c#L1788)
AFAIK, it uses `select` function.

This is very useful if we run the network polling/pushing in non-main thread. This makes the engine sends and receives the packets as soon as posible.

This can be done by adding `timeout` to `netcode_server_update` and `netcode_client_update`.
If the timeout is zero, two `update` functions run non-blocking and otherwise.

Thanks for considering.

**Comment by gafferongames** [comment]
If you can create a PR for this, I'd be happy to review it. Thanks!
