### ISSUE TITLE
Need help debugging why CI is broken

### ISSUE THREAD

**Issue by gafferongames** [mas-bandwidth/netcode#128]
It's not related to the code, but the CI scripts. Anybody want to volunteer? I'll give you maintainer privileges to do so

**Comment by gafferongames** [comment]
@dbechrd

**Comment by dbechrd** [comment]
I tried to fix it here: https://github.com/mas-bandwidth/netcode/pull/129 but it didn't work. I have no idea how Mac or Premake work, so I'm not sure I can help much with this. I always just put dependencies in my project folder on Windows and link to the precompiled .lib file directly to avoid weird system library path nonsense.
